### ISSUE TITLE
Does Not Support Pragma Statement Including `||`

### ISSUE THREAD

**Issue by bonedaddy** [NomicFoundation/truffle-flattener#64]
Declaring the pragma statement in the form of `pragma solidity ^0.5.0 || ^0.6.0 ;` causes `truffle-flattener` to fail, reporting the following error:

```
Error: Could not parse /tmp/t/ABDKMathQuad.sol for extracting its imports: ParserError: mismatched input '||' expecting ';' (5:23)
    at getDependencies (/home/solidity/.npm_modules/lib/node_modules/truffle-flattener/index.js:44:11)
    at dependenciesDfs (/home/solidity/.npm_modules/lib/node_modules/truffle-flattener/index.js:64:24)
    at async getSortedFilePaths (/home/solidity/.npm_modules/lib/node_modules/truffle-flattener/index.js:83:5)
    at async flatten (/home/solidity/.npm_modules/lib/node_modules/truffle-flattener/index.js:180:23)
    at async main (/home/solidity/.npm_modules/lib/node_modules/truffle-flattener/index.js:237:3)
```

To test you can use `truffle-flattener` on [this contract](https://github.com/abdk-consulting/abdk-libraries-solidity/blob/master/ABDKMathQuad.sol)

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
