### ISSUE TITLE
Invalid Path Problem

### ISSUE THREAD

**Issue by AbdulRafaySiddiqui** [NomicFoundation/truffle-flattener#69]
If the path for contracts contains space in the folder name, it gives an error.

The command below doesn't work it gives the following error because of the space in my **_Software Development_** folder name, when I rename the folder and remove the space it works fine

   `F:\Software Development\Dapps\monte-finance>truffle-flattener contracts/Monte.sol
    Error: ENOENT: no such file or directory, open 'f:/Software%20Development/Dapps/monte-finance/node_modules/@openzeppelin/contracts/utils/Context.sol'
        at Object.openSync (fs.js:457:3)
        at Object.readFileSync (fs.js:359:35)
        at resolve (C:\Users\Dell\AppData\Roaming\nvm\v12.16.1\node_modules\truffle-flattener\index.js:23:27)
        at async dependenciesDfs (C:\Users\Dell\AppData\Roaming\nvm\v12.16.1\node_modules\truffle-flattener\index.js:62:20)
        at async dependenciesDfs (C:\Users\Dell\AppData\Roaming\nvm\v12.16.1\node_modules\truffle-flattener\index.js:73:7)
        at async dependenciesDfs (C:\Users\Dell\AppData\Roaming\nvm\v12.16.1\node_modules\truffle-flattener\index.js:73:7)
        at async getSortedFilePaths (C:\Users\Dell\AppData\Roaming\nvm\v12.16.1\node_modules\truffle-flattener\index.js:83:5)
        at async flatten (C:\Users\Dell\AppData\Roaming\nvm\v12.16.1\node_modules\truffle-flattener\index.js:180:23)
        at async main (C:\Users\Dell\AppData\Roaming\nvm\v12.16.1\node_modules\truffle-flattener\index.js:237:3) {
      errno: -4058,
      syscall: 'open',
      code: 'ENOENT',
      path: 'f:/Software%20Development/Dapps/monte-finance/node_modules/@openzeppelin/contracts/utils/Context.sol'
    }`

This path works _**F:\Software-Development\Dapps\monte-finance**_

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
