### ISSUE TITLE
None of the sub-resolvers resolved "nft\node_modules\@openzeppelin\contracts\token\ERC721\ERC721Full.sol" location.

### ISSUE THREAD

**Issue by LucasBorges4** [NomicFoundation/truffle-flattener#72]
I m cant use truffle flattener because this error 

(node:14296) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14296) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
Error: None of the sub-resolvers resolved "nft\node_modules\@openzeppelin\contracts\token\ERC721\ERC721.sol" location.
    at ResolverEngine.<anonymous> (C:\Users\im\data\nft\node_modules\@resolver-engine\core\build\src\resolverengine.js:35:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\im\data\nft\node_modules\@resolver-engine\core\build\src\resolverengine.js:4:58)

**Comment by Tenoke** [comment]
Me n either. It seems like truffle-flattner is currently broken. I have no outside dependencies, truffle compiles, migrates fine but truffle-flattner  gives me errors on anything that has a dependency


```(node:10673) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10673) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
Error: Could not parse /home/tenoke/Documents/eth/~/contracts/ERC20/utils/SafeERC20.sol for extracting its imports: ParserError: missing ';' at '{' (52:18)
    at getDependencies (/home/tenoke/.nvm/versions/node/v15.12.0/lib/node_modules/truffle-flattener/index.js:44:11)
    at dependenciesDfs (/home/tenoke/.nvm/versions/node/v15.12.0/lib/node_modules/truffle-flattener/index.js:64:24)
    at async dependenciesDfs (/home/tenoke/.nvm/versions/node/v15.12.0/lib/node_modules/truffle-flattener/index.js:73:7)
    at async dependenciesDfs (/home/tenoke/.nvm/versions/node/v15.12.0/lib/node_modules/truffle-flattener/index.js:73:7)
    at async dependenciesDfs (/home/tenoke/.nvm/versions/node/v15.12.0/lib/node_modules/truffle-flattener/index.js:73:7)
    at async getSortedFilePaths (/home/tenoke/.nvm/versions/node/v15.12.0/lib/node_modules/truffle-flattener/index.js:83:5)
    at async flatten (/home/tenoke/.nvm/versions/node/v15.12.0/lib/node_modules/truffle-flattener/index.js:180:23)
    at async main (/home/tenoke/.nvm/versions/node/v15.12.0/lib/node_modules/truffle-flattener/index.js:237:3)```

**Comment by dougbtv** [comment]
+1

Similar kind of thing happening:

```
truffle-flattener contracts/boom.sol 
(node:378712) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:378712) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
Error: Could not parse /home/doug/codebase/matic/vtcards/node_modules/openzeppelin-solidity/contracts/utils/Counters.sol for extracting its imports: ParserError: missing ';' at '{' (26:18)
    at getDependencies (/usr/local/lib/node_modules/truffle-flattener/index.js:44:11)
    at dependenciesDfs (/usr/local/lib/node_modules/truffle-flattener/index.js:64:24)
    at async dependenciesDfs (/usr/local/lib/node_modules/truffle-flattener/index.js:73:7)
    at async getSortedFilePaths (/usr/local/lib/node_modules/truffle-flattener/index.js:83:5)
    at async flatten (/usr/local/lib/node_modules/truffle-flattener/index.js:180:23)
    at async main (/usr/local/lib/node_modules/truffle-flattener/index.js:237:3)
```

**Comment by liuhuanhui** [comment]
+1

**Comment by SYLing** [comment]
+1

**Comment by hedgehdev** [comment]
how to solve it?

**Comment by gfan8w** [comment]
how to fix it ?

**Comment by alcuadrado** [comment]
_Closing to clean up the repository. If this problem persists, please open a new issue with a clear explanation._
